### ISSUE TITLE
I wonder how this 'gocenter' makes each module has their only version

### ISSUE THREAD

**Issue by alexcdever** [jfrog/gocenter#1]
I wonder if some modules' creator didn't setup release tag for version, would  `gocenter` add it?

**Comment by jbaruch** [comment]
We won't include modules without release tags automatically. If they are requested manually (that means someone wants to use that module), we'll assign a `v0.0.0-timestamp-commithash` autogenerated version to the package we build. That's exactly how Go modules are generated by the `go` client.

**Comment by alexcdever** [comment]
Got it, thanks to reply 👍

**Comment by elioengcomp** [comment]
@alex-czp in addition to what was described by @jbaruch, any other commit hash being used as a dependency by another module will also be added to GoCenter in order to make the resolution of that module possible.

**Comment by alexcdever** [comment]
Thank you for answering my question. You are so nice!

**Comment by elioengcomp** [comment]
You are more than welcome! ;)

**Comment by elioengcomp** [comment]
@alex-czp I'm closing this issue. Please don't hesitate to reopen it or open a new one if you have additional questions.
