### ISSUE TITLE
jfrog & GOPROXY

### ISSUE THREAD

**Issue by jerome-laforge** [jfrog/gocenter#10]
To help us debug your issue please confirm the following :

- [X] I’ve read the [FAQ](https://github.com/jfrog/gocenter/wiki/Frequently-Asked-Questions).
- [X] I’ve explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
- [X] I’ve provided Go Module Name and Version (if applicable)

Hello,
jfrog is it compatible with GOPROXY?
as https://proxy.golang.org/
Yhx

**Comment by elioengcomp** [comment]
Hi @jerome-laforge 

Thank you for reaching out.

Yes, pointing `GOPROXY` to https://gocenter.io is one of the ways you can setup your environment to resolve dependencies from GoCenter. You can learn more by checking the Set Me Up instructions at https://gocenter.io.

**Comment by jerome-laforge** [comment]
Ok, thx for your quick answer.
Because I try do access to proxy via artifactory, and I get this error:
```
go: github.com/go-openapi/analysis@v0.19.0: unexpected status (https://artifactory/artifactory/api/go/go-proxy-official/github.com/go-openapi/analysis/@v/v0.19.0.info): 404 Not Found 
```

**Comment by elioengcomp** [comment]
You might have an issue with your Artifactory setup.

This is the result I got when pointing my `GOPROXY` environment variable to GoCenter directly.
```
→ export GOPROXY=https://gocenter.io/

→ go get github.com/go-openapi/analysis@v0.19.0
go: finding github.com/go-openapi/analysis v0.19.0
go: finding github.com/go-openapi/loads v0.17.0
go: finding github.com/go-openapi/strfmt v0.17.0
go: finding github.com/go-openapi/swag v0.17.0
go: finding github.com/go-openapi/jsonpointer v0.17.0
go: finding github.com/go-openapi/spec v0.17.0
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/pborman/uuid v1.2.0
go: finding github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329
go: finding github.com/asaskevich/govalidator v0.0.0-20180720115003-f9ffefc3facf
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: finding github.com/go-openapi/errors v0.17.0
go: finding github.com/go-openapi/analysis v0.0.0-20180825180245-b006789cd277
go: finding golang.org/x/text v0.3.0
go: finding github.com/globalsign/mgo v0.0.0-20180905125535-1ca0a4f7cbcb
go: finding github.com/go-openapi/jsonreference v0.17.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/PuerkitoBio/purell v1.1.0
go: finding github.com/google/uuid v1.0.0
go: finding golang.org/x/net v0.0.0-20181005035420-146acd28ed58
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/go-openapi/analysis v0.19.0
go: downloading github.com/go-openapi/spec v0.17.0
go: downloading github.com/go-openapi/jsonpointer v0.17.0
go: downloading github.com/go-openapi/swag v0.17.0
go: downloading github.com/go-openapi/strfmt v0.17.0
go: downloading github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329
go: downloading gopkg.in/yaml.v2 v2.2.1
go: downloading github.com/globalsign/mgo v0.0.0-20180905125535-1ca0a4f7cbcb
go: downloading github.com/go-openapi/errors v0.17.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/asaskevich/govalidator v0.0.0-20180720115003-f9ffefc3facf
go: downloading github.com/go-openapi/jsonreference v0.17.0
go: downloading github.com/PuerkitoBio/purell v1.1.0
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading golang.org/x/text v0.3.0
go: downloading golang.org/x/net v0.0.0-20181005035420-146acd28ed58
```

Can you try it just to confirm we don't have issues related to GoCenter? In case of issues with your Artifactory setup, I suggest you to open a support ticket so we can help you with that.

**Comment by jerome-laforge** [comment]
ok thx.
that works with gocenter without artifactory (except for `cannot load github.com/gin-gonic/gin: unexpected status (https://gocenter.io/github.com/gin-gonic/gin/@v/v1.3.1-0.20190424122141-202f8fc58af4.zip): 404 Not Found`  I supect because it is late commit)

**Comment by elioengcomp** [comment]
That 404 request will generate an inclusion request for that missing module. It might take a couple minutes for it to become available, but eventually it will be there and you will be able to fetch it. You can check the status via GoCenter UI. I have just checked and I can see that it is available now.
