### ISSUE TITLE
Stats last calculated: Invalid date

### ISSUE THREAD

**Issue by AlekSi** [jfrog/gocenter#17]
Currently at https://search.gocenter.io/stats:

![image](https://user-images.githubusercontent.com/11512/63446122-4e2d7b80-c442-11e9-862c-96ccce10c81f.png)

**Comment by ankushchadha** [comment]
Thanks @AlekSi for reporting this issue. We noticed that this bug is reproducible  on Firefox. Were you using Firefox or another browser?

Thanks

**Comment by AlekSi** [comment]
Safari 12.1.2 (14607.3.9) (WebKit 605.1.15), macOS 10.14.6 (18G87)

**Comment by DarthFennec** [comment]
I'm also noticing this on Safari.

![image](https://user-images.githubusercontent.com/1480189/63461108-cf6a1b80-c40c-11e9-8696-d7170fe0da3a.png)

**Comment by ankushchadha** [comment]
Hi @AlekSi - we deployed the fix to production today, thanks for reporting this issue. 

Thanks, @aarvyved for resolving this issue.
