### ISSUE TITLE
GoCenter doesn't support dynamic versions

### ISSUE THREAD

**Issue by ankushchadha** [jfrog/gocenter#29]
**Steps to reproduce:**
1. `export GOPROXY=https://gocenter.io`
2. `go get github.com/0xAX/notificator@master`

**Actual output:**
go get fails with the following:
_invalid version: reading https://gocenter.io/github.com/0x%21a%21x/notificator/@v/master.info: 404 Not Found_

**Expected output:** 
go get github.com/0xAX/notificator@master should be successful. Internally need to map the master to an actual version.

To help us debug your issue please confirm the following :

- [x] I’ve read the [FAQ](https://github.com/jfrog/gocenter/wiki/Frequently-Asked-Questions).
- [x] I’ve explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
- [x] I’ve provided Go Module Name and Version (if applicable)

**Comment by elioengcomp** [comment]
This capability was added to GoCenter. Users can now fetch from GoCenter modules using the following request formats:
- `go get <PATH>@<BRANCH>`
- `go get <PATH>@<COMMIT_HASH>`

GoCenter will translate the request to the actual SemVer compatible version and serve that instead.
