### ISSUE TITLE
Lack of Windows hints in setting up gocenter

### ISSUE THREAD

**Issue by glennsarti** [jfrog/gocenter#3]
Both the `To use GoCenter:` and `Set Me Up` sections are *nix / Mac focused.  These instructions will not work on Windows.  Given Go is cross platform, shouldn't there be instructions for Windows users too?

Piping to `sh` (or curl either really) won't work

![image](https://user-images.githubusercontent.com/5819622/52054460-8e590980-2597-11e9-8a01-8fa42a51f540.png)

Using `export` won't work

![image](https://user-images.githubusercontent.com/5819622/52054455-8bf6af80-2597-11e9-97b2-c14716215555.png)

---

To help us debug your issue please confirm the following :

- [x] I’ve read the [FAQ](https://github.com/jfrog/gocenter/wiki/Frequently-Asked-Questions).
- [x] I’ve explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
- [x] I’ve provided Go Module Name and Version (if applicable)

**Comment by elioengcomp** [comment]
Hi @glennsarti,

Thanks for you feedback. 

We are discussing this change with the UI team.

In the meantime, you can find instructions on how to setup `goc` on Windows at the [goc GitHub Page](https://github.com/jfrog/goc), by following the Download Directly From Bintray section.

**Comment by glennsarti** [comment]
Thanks @elioengcomp .  This might be out of scope for this particular issue, but the windows binary goc.exe is missing a lot of identifying information and isn't digitally signed.  While consumers may not care so much, I know many Windows enterprise-y people will look at this and immediately be suspicious of it.  Particularly AV products will flag unsigned/random looking exe's.

![image](https://user-images.githubusercontent.com/5819622/52101002-d2d6ba80-2614-11e9-89b4-5bece186fac2.png)

**Comment by elioengcomp** [comment]
Hi @glennsarti 

Thank you for pointing that out.

I have opened a new issue about it on the goc project.

**Comment by elioengcomp** [comment]
We have added instructions on how to download goc for Windows in the [goc](https://github.com/jfrog/goc) README.

We still plan to update the UI later on, that is why this issue is still open.

**Comment by elioengcomp** [comment]
Windows instructions were added to the UI.

![JFrog_GoCenter_-_The_Central_Go_Modules_Repository](https://user-images.githubusercontent.com/23169901/61723485-16d38e00-ad21-11e9-924e-5454a521541e.png)

**Comment by ankushchadha** [comment]
Hi @glennsarti - With the new set of changes in GoCenter, there is no reason to use goc anymore. 

Once the GOPROXY is set to https://gocenter.io, GoCenter will be able to serve modules and avoid 404s for valid modules even if they don't exist in GoCenter.

**Comment by glennsarti** [comment]
Thanks @elioengcomp !!
