### ISSUE TITLE
Feature Request: Full-Text Search

### ISSUE THREAD

**Issue by Dattax** [jfrog/gocenter#30]
**Issue:** when searching for a module in Go Center, the search results often show a short description of the module underneath the module name. I noticed however that if someone trys to search using that description, the relevant module doesn't come up. 

**Steps to reproduce:** go to gocenter.io and search for "logrus". The desc says "Structured, pluggable logging for Go." copy and paste that same description into the search area and you'll notice that logrus app does not show up in results.

**To fix:** we should add the full-text search capabilities: https://medium.com/@MentorMate/elasticsearch-how-to-add-full-text-search-to-your-database-ee2f3ea4d3f3

**Comment by ankushchadha** [comment]
The feature rolled out to prod today.
