### ISSUE TITLE
unable to download github.com/operator-framework/operator-sdk@v0.12.0

### ISSUE THREAD

**Issue by Sibilia** [jfrog/gocenter#37]
To help us debug your issue please confirm the following :

- [x] I’ve read the [FAQ](https://github.com/jfrog/gocenter/wiki/Frequently-Asked-Questions).
- [x] I’ve explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
- [x] I’ve provided Go Module Name and Version (if applicable)

Hi,

I am unable to download the go package github.com/operator-framework/operator-sdk@v0.12.0. Could you please load the missing version (v0.12.0) for the module github.com/operator-framework/operator-sdk.
```shell
$ echo $GOPROXY
https://gocenter.io  
$ go get -v github.com/operator-framework/operator-sdk@v0.12.0
go: github.com/operator-framework/operator-sdk@v0.12.0: reading https://gocenter.io/github.com/operator-framework/operator-sdk/@v/v0.12.0.mod: 404 Not Found
$ export GOPROXY=""
$ go get -v github.com/operator-framework/operator-sdk@v0.12.0
go: finding github.com/operator-framework/operator-sdk v0.12.0
go: downloading github.com/operator-framework/operator-sdk v0.12.0
go: extracting github.com/operator-framework/operator-sdk v0.12.0
```

Thanks,
Ilya S

**Comment by elioengcomp** [comment]
Hi @Sibilia ,

Thank you for your message.

GoCenter performs some validation checks and only serves healthy modules. The module you are looking for has some invalid requirements that are being detected by those checks and that is why it is not being served by GoCenter.

You can mimic GoCenter validation rules logic and see the requirement issue by running the commands below:

```
→ export GOPROXY=direct
→ export GOSUMDB=off
→ go get github.com/operator-framework/operator-sdk@v0.12.0
go: finding github.com/operator-framework/operator-sdk v0.12.0
go: downloading github.com/operator-framework/operator-sdk v0.12.0
go: extracting github.com/operator-framework/operator-sdk v0.12.0
go get: github.com/operator-framework/operator-sdk@v0.12.0 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

You can see that and also information for all `github.com/operator-framework/operator-sdk` versions on GoCenter at https://search.gocenter.io/github.com~2Foperator-framework~2Foperator-sdk/info

**Comment by Sibilia** [comment]
thanks

**Comment by elioengcomp** [comment]
You are welcome.
