### ISSUE TITLE
Go Center get wrong confd version, cause import projectcalico/node new version failed

### ISSUE THREAD

**Issue by shuaizhilin** [jfrog/gocenter#50]
This Go module do not actually have the latest version available about projectcalico/node and projectcalico/felix
https://search.gocenter.io/github.com/projectcalico/node?version=v3.9.0-0.dev%2Bincompatible&tab=versions
https://search.gocenter.io/github.com/projectcalico/felix?version=v3.13.0-0.dev%2Bincompatible&tab=versions

**projectcalico/node:**
![image](https://user-images.githubusercontent.com/12966967/89153530-a4ce8f80-d597-11ea-9e1a-96ace771bc4b.png)

**ERROR Log:**
![image](https://user-images.githubusercontent.com/12966967/89153405-5c16d680-d597-11ea-9a8c-286c1ff355e1.png)

**projectcalico/felix:**
![image](https://user-images.githubusercontent.com/12966967/89153621-d5aec480-d597-11ea-8609-ab0fceeb4b61.png)

**ERROR Log:**
![image](https://user-images.githubusercontent.com/12966967/89153670-ee1edf00-d597-11ea-9c22-65dfc0464c87.png)

**Comment by elioengcomp** [comment]
Hi @blankskygithub 

Thank you for your message.

At this moment, GoCenter will not serve Go Module with bad requirements. As you can see in their [mod files](https://github.com/projectcalico/node/blob/v3.15.1/go.mod) and in the error messages, those modules have invalid requirements (the ones with only zeros in their versions). The authors are using replace statements to fix the bad requirements but those statements are ignored by other modules when they are used as dependencies, that is why GoCenter is not serving them.

We are working to change that behavior in GoCenter to serve those modules as well so the missing modules you pointed out will also be available soon. You can find more information about that discussion at [#43](https://github.com/jfrog/gocenter/issues/43)
