### ISSUE TITLE
github.com/nats-io/nats-server missing 2.x version

### ISSUE THREAD

**Issue by flymoondust** [jfrog/gocenter#51]
How to introduce new version of nats-server??
gocenter's website is https://search.gocenter.io/github.com/nats-io/nats-server?version=v2.0.0-RC14%2Bincompatible&tab=versions

nats-server's website is https://github.com/nats-io/nats-server

Now, gocenter miss 2.x versions of nats-server.
Please reply ASAP,thanks very much.

**Comment by elioengcomp** [comment]
Hi @flymoondust 

Thanks for you message.

I can see several v2.x versions for that module in GoCenter: https://search.gocenter.io/github.com/nats-io/nats-server/v2?version=v2.1.8-0.20200701221136-774da7f02108&tab=versions 

Keep in mind that to follow Go Modules semantic versioning rules, the authors changed the module path to `github.com/nats-io/nats-server/v2`

Which versions are you missing there?

**Comment by flymoondust** [comment]
it's my fault,i can see it's in v2 now. Thanks for replying. The issue can be closed now.&nbsp;



---Original---

**Comment by elioengcomp** [comment]
Let us know if you have additional questions.
