### ISSUE TITLE
Feature Request/Clearer error message on processing module error

### ISSUE THREAD

**Issue by chanpl** [jfrog/gocenter#7]
I feel error message from GoCenter on processing module could be clearer and more descriptive. 

Example: https://gocenter.jfrog.com/github.com~2Frwynn~2Fmgo/versions

It was saying:
_Failed to process module github.com/rwynn/mgo v0.0.0-20190203195949-55e8fd85e7e2
Execution did not publish module github.com/rwynn/mgo v0.0.0-20190203195949-55e8fd85e7e2 to GoCenter_

Perhaps a better error message is preferred. Meanwhile, what's exact problem for this module here?

**Comment by ankushchadha** [comment]
Thanks, @chanpl for reporting this issue. 

GoCenter was unable to process github.com/rwynn/mgo v0.0.0-20190203195949-55e8fd85e7e2 because the correct module name is github.com/globalsign/mgo. 

Here is the detailed output

```
[Info] Running 'go mod graph' in...
[Debug] Initializing protocol regexp
[Debug] Initializing not found regexp
[Debug] Initializing unrecognized import path regexp
[Debug] Initializing unknown revision regexp
go: finding github.com/rwynn/mgo v0.0.0-20190203195949-55e8fd85e7e2
go: github.com/rwynn/mgo@v0.0.0-20190203195949-55e8fd85e7e2: parsing go.mod: unexpected module path "github.com/globalsign/mgo"
go: error loading module requirements
```
This feedback is very important to us. We currently display the first few lines of the detailed error message and it doesn't give the best UX. We need to make the error messages more intuitive.

**Comment by chanpl** [comment]
Thanks @ankushchadha 
Good to hear that JFrog acknowledged this issue and thanks for checking the error for me.

**Comment by chanpl** [comment]
Hi @ankushchadha ,

Sorry for bothering you, but I have one more question. The author has pushed a new commit, but GoCenter seems not detecting. We are expecting GoCenter will process github.com/rwynn/mgo@v0.0.0-20190318130802-4743670bc61d. Re-submitting 'Add' request seems not help. May I know why? Maybe share error message with me again if you don't mind. Thanks in advance and sorry for the inconvenience.

**Comment by ankushchadha** [comment]
@chanpl - we are always there to help. When a module is added to GoCenter via the 'Add' request, we check for recent 20 tags and add them. In the case of github.com/rwynn/mgo, the tags are not semver compliant (example: v1.2.3), hence new versions were not added. 

commit hash of a project gets added if there are consumers of that specific version or if the project is added to GoCenter for the first time.

For now, we added the specific version github.com/rwynn/mgo@v0.0.0-20190318130802-4743670bc61d and it's now available on GoCenter.

**Comment by elioengcomp** [comment]
@chanpl we recommend that you start tagging your releases following the [semantic versioning](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) best practices for Go Modules. GoCenter will see new tags as missing versions and you will be able to request them to be processed via the GoCenter UI.

**Comment by chanpl** [comment]
Thanks @ankushchadha for uploading the package manually for us.
Sure @elioengcomp , thanks for your advice.

**Comment by elioengcomp** [comment]
@chanpl let's keep this issue opened to track the error message improvements.

**Comment by aln8** [comment]
For some reason, our team get some issue with 
```
go: github.com/micro/go-plugins@v1.1.0: unexpected status (https://gocenter.io/github.com/micro/go-plugins/@v/v1.1.0.info): 404 Not Found
go: github.com/nats-io/nats.go@v1.7.2: unexpected status (https://gocenter.io/github.com/nats-io/nats.go/@v/v1.7.2.info): 404 Not Found
go: github.com/micro/go-grpc@v1.0.1: unexpected status (https://gocenter.io/github.com/micro/go-grpc/@v/v1.0.1.info): 404 Not Found
```

Meanwhile, here is our go.mod
```
go 1.12

replace (
	github.com/golang/lint => golang.org/x/lint v0.0.0-20190313153728-d0100b6bd8b3
	github.com/testcontainers/testcontainer-go => github.com/testcontainers/testcontainers-go v0.0.2
)

require (
	github.com/micro/go-grpc v1.0.1
	github.com/micro/go-micro v1.3.1
	github.com/micro/go-plugins v1.1.0
)
```

When we use goproxy.io seems there is no issue. But our project is based on jFrog, we'd perfer using gocenter as remote repo that we can use virtual repo along with some local project build.

I'm very curious about what's going on behind it.

**Comment by elioengcomp** [comment]
Hi @Marsyyh,

At this moment, we do not serve in GoCenter modules that have requirements issues.

If you try running `go get -d github.com/micro/go-grpc@v1.0.1` resolving from GitHub you will get the following result:

```
→ go get -d github.com/micro/go-grpc@v1.0.1
go: finding github.com/micro/go-grpc v1.0.1
go: finding github.com/armon/circbuf v0.0.0-20190214190532-5111143e8da2
go: finding github.com/go-ini/ini v1.42.0
...
go: finding github.com/golang/lint v0.0.0-20190313153728-d0100b6bd8b3
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding github.com/hashicorp/go-discover v0.0.0-20190403160810-22221edb15cd
...
go: error loading module requirements
```

The other modules have similar issues and that is why they are not being served by GoCenter. 

The rule of thumb is, if a basic `go get` command fails when resolving from source, GoCenter will consider the module in a bad state and will not serve it.

**Comment by ankushchadha** [comment]
Closing this since this has been fixed in production.  A user will be able to download the log file if there is processing or validation failure. 

Example - Go to https://search.gocenter.io/helm.sh~2Fhelm/info?version=v3.0.0-beta.3.0.20191003164502-e247d3050374%2Bincompatible
1. Go to versions tab
2. Go to a version that failed and click on the ! icon, a new popup will appear via which users can download the log file.

Thanks @MitaliBo
