### ISSUE TITLE
Is it open source?

### ISSUE THREAD

**Issue by opinionsDazzle** [jfrog/gocenter#8]
To help us debug your issue please confirm the following :

- [ ] I’ve read the [FAQ](https://github.com/jfrog/gocenter/wiki/Frequently-Asked-Questions).
- [ ] I’ve explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
- [ ] I’ve provided Go Module Name and Version (if applicable)

**Comment by jbaruch** [comment]
Here's what open-source and what's not:

-  The code of GoCenter itself is not open-source. It is a cloud service, it is not designed to be downloaded and built, and it's free, so basically who cares, but no, you can't see the source code.

- The `goc` client which adds a fallback to cloning the sources from vsc to the regular `go` client is open-source under Apache 2.

Hope that clarifies it.
