### ISSUE TITLE
Sort versions semantically instead of lexically

### ISSUE THREAD

**Issue by elioengcomp** [jfrog/gocenter#9]
As pointed out by `thepudds` on the gocenter slack channel:

> You might also want to sort that table so that is shows most recent versions first? E.g., maybe use something like:
https://github.com/rogpeppe/go-internal/blob/master/semver/semver.go#L115 (edited) 
Right now, it looks like a purely lexical sort order and ignoring the syntax and precedence of semver, which means a v0.11.0 is at the bottom while a v0.9.0 is near the top, as seen here:
https://search.gocenter.io/github.com~2Fgoph~2Flogur/versions

To help us debug your issue please confirm the following :

- [x] I’ve read the [FAQ](https://github.com/jfrog/gocenter/wiki/Frequently-Asked-Questions).
- [x] I’ve explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
- [x] I’ve provided Go Module Name and Version (if applicable)

**Comment by ankushchadha** [comment]
Fixes rolled out to prod. Backend fixes were rolled out last week.
